##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://www.lib.uidaho.edu
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /digital/fwres
# location of code, the full url to your github repository
source-code: https://github.com/uidaholib/documents-digital-collections-template

# url to the shared assets folder on mainweb
digital-assets: https://www.lib.uidaho.edu/assets

##########
# Search Setting
#
# set to true to use elastic search box in nav. Collection search.json must be added to the search Sources! Check config-search-index for configuration.
# if collection is not in the index, leave blank to use local lunr search instead.
central-search: true

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Idaho Forest, Wildlife, and Range Experiment Station Collection
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: "UI-led research on topics ranging from Idaho's forests and hydrology to rangeland, fisheries, and wildlife, published from 1954 to the present"
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Over 200 documents and reports created by faculty in the UI Forestry Department of the College of Natural Resources, 1954 to the present."  
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: pinus ponderosa; ponderosa pine; artemisia; artemisia tridentata; endangered species; forestry
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: CollectionBuilder

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: fwres
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "University of Idaho Library Digital Collections"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/images/ui_library_horizontal.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/liblogo_white.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CODEOWNERS, utilities/]
# compress CSS output
sass:
  style: compressed
